name: palm_codes
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  after_layout: ^1.2.0
  auto_route: ^8.2.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.3
  get_it: ^7.7.0
  injectable: ^2.4.2
  logger: ^2.3.0
  pull_to_refresh_flutter3: ^2.0.2
  shared_preferences: ^2.2.3
  skeletonizer: ^1.3.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - env/.env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
